name: Build and Deploy Develop Docker Container

on:
  push:
    branches:
      - develop

# Grants GitHub the permissions to write packages to your repo's built-in registry
permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  # These will automatically point to your GitHub packages page: ghcr.io/username/webapp and server
  WEBAPP_IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/webapp
  SERVER_IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/server

jobs:
  build-publish-webapp:
    name: Build and deploy webapp container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Logs in using GitHub's built-in temporary token automatically
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.WEBAPP_IMAGE_NAME }}
          tags: |
            type=raw,value=develop

      # Builds and pushes the Webapp image using the monorepo root as context
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        id: build
        with:
          context: .
          file: ./packages/webapp/Dockerfile
          platforms: linux/amd64
          push: true
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}

      - name: Export digest
        run: |
          mkdir -p /tmp/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "/tmp/digests/${digest#sha256:}"

      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: digests-webapp
          path: /tmp/digests/*
          if-no-files-found: error
          retention-days: 1

  build-publish-server:
    name: Build and deploy server container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Logs in using GitHub's built-in temporary token automatically
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker Server
        id: meta-server
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.SERVER_IMAGE_NAME }}
          tags: |
            type=raw,value=develop

      # Builds and pushes the Server image using the monorepo root as context
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        id: build
        with:
          context: .
          file: ./packages/server/Dockerfile
          platforms: linux/amd64
          push: true
          labels: ${{ steps.meta-server.outputs.labels }}
          tags: ${{ steps.meta-server.outputs.tags }}

      - name: Export digest
        run: |
          mkdir -p /tmp/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "/tmp/digests/${digest#sha256:}"

      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: digests-server
          path: /tmp/digests/*
          if-no-files-found: error
          retention-days: 1
